services:
  authapi:
    build:
      context: ..
      dockerfile: AuthenticationAPI/Dockerfile
    container_name: auth-api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Data Source=HumanResourceManagement.db
    volumes:
      - sqlite-data:/app/data
    restart: unless-stopped
    mem_limit: 512m

volumes:
  sqlite-data:
    name: auth-sqlitedata
